# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!
from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 442)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(10, 10, 441, 411))
        self.tabs.setTabsClosable(False)
        self.tabs.setObjectName("tabs")
        self.indexTab = QtWidgets.QWidget()
        self.indexTab.setObjectName("indexTab")
        self.layoutWidget_2 = QtWidgets.QWidget(self.indexTab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 413, 141))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.indexComboType = QtWidgets.QComboBox(self.layoutWidget_2)
        self.indexComboType.setObjectName("indexComboType")
        self.indexComboType.addItems(['JPG', 'PNG'])
        self.gridLayout_2.addWidget(self.indexComboType, 1, 2, 1, 2)
        self.indexLabelType = QtWidgets.QLabel(self.layoutWidget_2)
        self.indexLabelType.setObjectName("indexLabelType")
        self.gridLayout_2.addWidget(self.indexLabelType, 0, 2, 1, 1)
        self.indexButtonSrc = QtWidgets.QPushButton(self.layoutWidget_2)
        self.indexButtonSrc.setObjectName("indexButtonSrc")
        self.gridLayout_2.addWidget(self.indexButtonSrc, 1, 1, 1, 1)
        self.indexLabelDst = QtWidgets.QLabel(self.layoutWidget_2)
        self.indexLabelDst.setObjectName("indexLabelDst")
        self.gridLayout_2.addWidget(self.indexLabelDst, 2, 0, 1, 1)
        self.indexButtonDst = QtWidgets.QPushButton(self.layoutWidget_2)
        self.indexButtonDst.setObjectName("indexButtonDst")
        self.gridLayout_2.addWidget(self.indexButtonDst, 3, 3, 1, 1)
        self.indexEditSrc = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.indexEditSrc.setObjectName("indexEditSrc")
        self.gridLayout_2.addWidget(self.indexEditSrc, 1, 0, 1, 1)
        self.indexEditDst = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.indexEditDst.setObjectName("indexEditDst")
        self.gridLayout_2.addWidget(self.indexEditDst, 3, 0, 1, 3)
        self.indexLabelSrc = QtWidgets.QLabel(self.layoutWidget_2)
        self.indexLabelSrc.setObjectName("indexLabelSrc")
        self.gridLayout_2.addWidget(self.indexLabelSrc, 0, 0, 1, 1)
        self.indexImageView = QtWidgets.QScrollArea(self.indexTab)
        self.indexImageView.setGeometry(QtCore.QRect(11, 186, 411, 190))
        self.indexImageView.setWidgetResizable(True)
        self.indexImageView.setObjectName("indexImageView")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 409, 188))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.indexScroll = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.indexScroll.setGeometry(QtCore.QRect(390, 0, 16, 187))
        self.indexScroll.setOrientation(QtCore.Qt.Vertical)
        self.indexScroll.setObjectName("indexScroll")
        self.indexImageView.setWidget(self.scrollAreaWidgetContents)
        self.indexLabelImages = QtWidgets.QLabel(self.indexTab)
        self.indexLabelImages.setGeometry(QtCore.QRect(17, 164, 47, 13))
        self.indexLabelImages.setObjectName("indexLabelImages")
        self.tabs.addTab(self.indexTab, "")
        self.alignTab = QtWidgets.QWidget()
        self.alignTab.setObjectName("alignTab")
        self.alignTabs = QtWidgets.QTabWidget(self.alignTab)
        self.alignTabs.setGeometry(QtCore.QRect(5, 160, 425, 221))
        self.alignTabs.setObjectName("alignTabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.alignImageView = QtWidgets.QScrollArea(self.tab)
        self.alignImageView.setGeometry(QtCore.QRect(4, 4, 411, 190))
        self.alignImageView.setWidgetResizable(True)
        self.alignImageView.setObjectName("alignImageView")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 409, 188))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.alignScrollImage = QtWidgets.QScrollBar(self.scrollAreaWidgetContents_3)
        self.alignScrollImage.setGeometry(QtCore.QRect(390, 0, 16, 187))
        self.alignScrollImage.setOrientation(QtCore.Qt.Vertical)
        self.alignScrollImage.setObjectName("alignScrollImage")
        self.alignImageView.setWidget(self.scrollAreaWidgetContents_3)
        self.alignTabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.alignConflictView = QtWidgets.QScrollArea(self.tab_2)
        self.alignConflictView.setGeometry(QtCore.QRect(4, 4, 411, 190))
        self.alignConflictView.setWidgetResizable(True)
        self.alignConflictView.setObjectName("alignConflictView")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 409, 188))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.alignScrollConflict = QtWidgets.QScrollBar(self.scrollAreaWidgetContents_5)
        self.alignScrollConflict.setGeometry(QtCore.QRect(390, 0, 16, 187))
        self.alignScrollConflict.setOrientation(QtCore.Qt.Vertical)
        self.alignScrollConflict.setObjectName("alignScrollConflict")
        self.alignConflictView.setWidget(self.scrollAreaWidgetContents_5)
        self.alignTabs.addTab(self.tab_2, "")
        self.layoutWidget = QtWidgets.QWidget(self.alignTab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 411, 137))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.alignLabelType = QtWidgets.QLabel(self.layoutWidget)
        self.alignLabelType.setObjectName("alignLabelType")
        self.gridLayout.addWidget(self.alignLabelType, 0, 0, 1, 1)
        self.alignLabelType_2 = QtWidgets.QLabel(self.layoutWidget)
        self.alignLabelType_2.setObjectName("alignLabelType_2")
        self.gridLayout.addWidget(self.alignLabelType_2, 0, 3, 1, 1)
        self.alignEditSrc = QtWidgets.QLineEdit(self.layoutWidget)
        self.alignEditSrc.setObjectName("alignEditSrc")
        self.gridLayout.addWidget(self.alignEditSrc, 1, 0, 1, 2)
        self.alignButtonSrc = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignButtonSrc.sizePolicy().hasHeightForWidth())
        self.alignButtonSrc.setSizePolicy(sizePolicy)
        self.alignButtonSrc.setObjectName("alignButtonSrc")
        self.gridLayout.addWidget(self.alignButtonSrc, 1, 2, 1, 1)
        self.alignComboType = QtWidgets.QComboBox(self.layoutWidget)
        self.alignComboType.setObjectName("alignComboType")
        self.alignComboType.addItems(['JPG', 'PNG'])
        self.gridLayout.addWidget(self.alignComboType, 1, 3, 1, 2)
        self.alignLabelDst = QtWidgets.QLabel(self.layoutWidget)
        self.alignLabelDst.setObjectName("alignLabelDst")
        self.gridLayout.addWidget(self.alignLabelDst, 2, 0, 1, 1)
        self.alignEditDst = QtWidgets.QLineEdit(self.layoutWidget)
        self.alignEditDst.setObjectName("alignEditDst")
        self.gridLayout.addWidget(self.alignEditDst, 3, 0, 1, 4)
        self.alignButtonDst = QtWidgets.QPushButton(self.layoutWidget)
        self.alignButtonDst.setObjectName("alignButtonDst")
        self.gridLayout.addWidget(self.alignButtonDst, 3, 4, 1, 1)
        self.alignLabelWidth = QtWidgets.QLabel(self.layoutWidget)
        self.alignLabelWidth.setObjectName("alignLabelWidth")
        self.gridLayout.addWidget(self.alignLabelWidth, 4, 0, 1, 1)
        self.alignLabelHeight = QtWidgets.QLabel(self.layoutWidget)
        self.alignLabelHeight.setObjectName("alignLabelHeight")
        self.gridLayout.addWidget(self.alignLabelHeight, 4, 1, 1, 1)
        self.alignLabelScale = QtWidgets.QLabel(self.layoutWidget)
        self.alignLabelScale.setObjectName("alignLabelScale")
        self.gridLayout.addWidget(self.alignLabelScale, 4, 3, 1, 1)
        self.alignEditWidth = QtWidgets.QLineEdit(self.layoutWidget)
        self.alignEditWidth.setObjectName("alignEditWidth")
        self.gridLayout.addWidget(self.alignEditWidth, 5, 0, 1, 1)
        self.alignEditHeight = QtWidgets.QLineEdit(self.layoutWidget)
        self.alignEditHeight.setObjectName("alignEditHeight")
        self.gridLayout.addWidget(self.alignEditHeight, 5, 1, 1, 2)
        self.alignEditScale = QtWidgets.QLineEdit(self.layoutWidget)
        self.alignEditScale.setObjectName("alignEditScale")
        self.gridLayout.addWidget(self.alignEditScale, 5, 3, 1, 2)
        self.tabs.addTab(self.alignTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        self.alignTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.indexButtonSrc.clicked.connect(self.on_click)
        self.indexButtonDst.clicked.connect(self.on_click)
        self.alignButtonSrc.clicked.connect(self.on_click)
        self.alignButtonDst.clicked.connect(self.on_click)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Face Time-lapse Tool"))
        self.indexLabelType.setText(_translate("MainWindow", "Image Type"))
        self.indexButtonSrc.setText(_translate("MainWindow", "Browse"))
        self.indexLabelDst.setText(_translate("MainWindow", "Destination Directory"))
        self.indexButtonDst.setText(_translate("MainWindow", "Browse"))
        self.indexLabelSrc.setText(_translate("MainWindow", "Source Directory"))
        self.indexLabelImages.setText(_translate("MainWindow", "Images"))
        self.tabs.setTabText(self.tabs.indexOf(self.indexTab), _translate("MainWindow", "Index Files"))
        self.alignTabs.setTabText(self.alignTabs.indexOf(self.tab), _translate("MainWindow", "Images"))
        self.alignTabs.setTabText(self.alignTabs.indexOf(self.tab_2), _translate("MainWindow", "Conflicts"))
        self.alignLabelType.setText(_translate("MainWindow", "Source Directory"))
        self.alignLabelType_2.setText(_translate("MainWindow", "Image Type"))
        self.alignButtonSrc.setText(_translate("MainWindow", "Browse"))
        self.alignLabelDst.setText(_translate("MainWindow", "Destination Directory"))
        self.alignButtonDst.setText(_translate("MainWindow", "Browse"))
        self.alignLabelWidth.setText(_translate("MainWindow", "Width"))
        self.alignLabelHeight.setText(_translate("MainWindow", "Height"))
        self.alignLabelScale.setText(_translate("MainWindow", "Eye Distance"))
        self.tabs.setTabText(self.tabs.indexOf(self.alignTab), _translate("MainWindow", "Align Images"))


    def on_click(self):
        sender = MainWindow.sender()
        directory = QtWidgets.QFileDialog.getExistingDirectory(QtWidgets.QFileDialog(), "Select directory")
        if sender.objectName() == "indexButtonSrc":
            self.indexEditSrc.setText(directory)
        elif sender.objectName() == "indexButtonDst":
            self.indexEditDst.setText(directory)
        elif sender.objectName() == "alignButtonSrc":
            self.alignEditSrc.setText(directory)
        elif sender.objectName() == "alignButtonDst":
            self.alignEditDst.setText(directory)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
